version: '3.8'

services:
  tut1:
    env_file:
      - .env
    container_name: backend
    image: nginx
    ports:
      - "1080:80"
    volumes:
      - /opt/source_code:/app/lode/source_code:rw

  tut2:
    env_file:
      - .env
    container_name: backend2
    image: nginx
    ports:
      - "2080:80"
    volumes:
      - /opt/source_code:/app/lode/source_code:rw


